# Generated by Django 4.0.3 on 2022-03-22 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('BTC', 'Bitcoin'), ('CRO', 'Cro'), ('ETH', 'Ethereum')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='main', max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('0', 'Outgoing transaction'), ('1', 'Ingoing transaction')], default='0', max_length=3)),
                ('value', models.FloatField(default=0)),
                ('change', models.FloatField(default=0)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('currency_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TCWallet.currencywallet')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddField(
            model_name='currencywallet',
            name='wallet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='TCWallet.wallet'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique-wallet-per-user'),
        ),
        migrations.AddConstraint(
            model_name='currencywallet',
            constraint=models.UniqueConstraint(fields=('currency', 'wallet'), name='unique-currency-in-wallet'),
        ),
    ]
